-- DROP TABLE `REVERSI_PLAYER`;
CREATE TABLE `REVERSI_PLAYER` (
  `PLAYER_ID` VARCHAR(256) NOT NULL PRIMARY KEY,
  `IP` VARCHAR(256) NOT NULL,
  `MODIFY_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATE_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX `REVERSI_PLAYER_PLAYER_ID_INDEX`
ON `REVERSI_PLAYER`(`PLAYER_ID`);
CREATE INDEX `REVERSI_PLAYER_ID_INDEX`
ON `REVERSI_PLAYER`(`IP`);
CREATE INDEX `REVERSI_PLAYER_MODIFY_DATE_INDEX`
ON `REVERSI_PLAYER`(`MODIFY_DATE`);
CREATE INDEX `REVERSI_PLAYER_CREATE_DATE_INDEX`
ON `REVERSI_PLAYER`(`CREATE_DATE`);