-- DROP TABLE `REVERSI_PLAYER`;
CREATE TABLE `REVERSI_PLAYER` (
  `PLAYER_ID` varchar(256) NOT NULL,
  `MODIFY_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
);