-- DROP TABLE `REVERSI_ACCESS_LOG`;
CREATE TABLE `REVERSI_ACCESS_LOG` (
  `ID` INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  `ACCESS_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IP` VARCHAR(256) NOT NULL,
  `URI` VARCHAR(256) NOT NULL,
  `RESTRICTION` BOOLEAN NOT NULL
);
CREATE INDEX `REVERSI_ACCESS_LOG_ID_INDEX`
ON `REVERSI_ACCESS_LOG`(`ID`);
CREATE INDEX `REVERSI_ACCESS_LOG_ACCESS_DATE_INDEX`
ON `REVERSI_ACCESS_LOG`(`ACCESS_DATE`);
CREATE INDEX `REVERSI_ACCESS_LOG_IP_INDEX`
ON `REVERSI_ACCESS_LOG`(`IP`);
CREATE INDEX `REVERSI_ACCESS_LOG_URI_INDEX`
ON `REVERSI_ACCESS_LOG`(`URI`);
CREATE INDEX `REVERSI_ACCESS_LOG_RESTRICTION_INDEX`
ON `REVERSI_ACCESS_LOG`(`RESTRICTION`);