-- DROP TABLE `REVERSI_ACCESS_RESTRICTION`;
CREATE TABLE `REVERSI_ACCESS_RESTRICTION` (
  `IP` VARCHAR(256) NOT NULL PRIMARY KEY,
  `RESTRICTION_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX `REVERSI_ACCESS_RESTRICTION_IP_INDEX`
ON `REVERSI_ACCESS_RESTRICTION`(`IP`);
CREATE INDEX `REVERSI_ACCESS_RESTRICTION_RESTRICTION_DATE_INDEX`
ON `REVERSI_ACCESS_RESTRICTION`(`RESTRICTION_DATE`);